allow_remote_control yes
enabled_layouts splits
copy_on_select yes
#----------------------------------------------------------------------
tab_bar_edge top
tab_bar_style       custom
tab_bar_min_tabs 1
tab_separator       ""
tab_title_template  "    {index} [{title}]    "
window_margin_width 4
single_window_margin_width 0
#----------------------------------------------------------------------
map --new-mode normal Ctrl+Alt+Shift+Space
map --mode normal y copy_to_clipboard
map --mode normal p paste_from_clipboard
map --mode normal h send_key left
map --mode normal l send_key right
map --mode normal j send_key down
map --mode normal k send_key up
map --mode normal Ctrl+h send_key Ctrl+left
map --mode normal Ctrl+l send_key Ctrl+right
map --mode normal Ctrl+j send_key Ctrl+down
map --mode normal Ctrl+k send_key Ctrl+up

map --mode normal 0 send_key Ctrl+a
map --mode normal $ send_key Ctrl+e

map --new-mode insert --on-unknown passthrough f23
map --mode normal i push_keyboard_mode insert
map --mode normal w push_keyboard_mode windows
map --mode normal tab push_keyboard_mode tabs
#----------------------------------------------------------------------
map --mode insert --when-focus-on title:nvim Alt+Esc pop_keyboard_mode
map --mode insert --when-focus-on not(title:nvim) Esc pop_keyboard_mode
#----------------------------------------------------------------------
map --new-mode windows f25
map --mode windows esc pop_keyboard_mode
map --mode windows h neighboring_window left
map --mode windows j neighboring_window down
map --mode windows k neighboring_window up
map --mode windows l neighboring_window right

map --mode windows Shift+h move_window left
map --mode windows Shift+j move_window down
map --mode windows Shift+k move_window up
map --mode windows Shift+l move_window right

map --mode windows Shift+= resize_window taller 2
map --mode windows - resize_window shorter 2
map --mode windows Shift+, resize_window narrower 2
map --mode windows Shift+. resize_window wider 2

map --mode windows "_" layout_action maximize vertical
map --mode windows "|" layout_action maximize horizontal

map --mode windows v launch --location=vsplit
map --mode windows s launch --location=hsplit

map --mode windows slash layout_action rotate

map --mode windows n launch --location split
map --mode windows d close_window
#----------------------------------------------------------------------
map --new-mode tabs f24
map --mode tabs tab launch --type=tab
map --mode tabs d close_tab
map --mode tabs [ previous_tab
map --mode tabs ] next_tab
map --mode tabs Shift+[ move_tab_backward
map --mode tabs SHift+] move_tab_forward
map --mode tabs esc pop_keyboard_mode
map --mode tabs r combine : send_text all kitty @ set-tab-title ""\x1b[D : launch --type=background wtype -k Escape -k i
#----------------------------------------------------------------------
